### ISSUE TITLE
 RuntimeError: Error compiling objects for extension when run ' python setup.py build develop --no-deps '

### ISSUE THREAD

**Issue by ShirleyHe2020** [megvii-model/LabelEnc#4]
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    setup(
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/qian/anaconda3/envs/LabelEnc/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
(LabelEnc) qian@debian:~/LabelEnc$

**Comment by P-HL** [comment]
Hello, I meet the same problem, and I think it is because the pytorch version is to high. My environment is torch==1.11.0+cu102 torchvision==0.12.0+cu102 torchaudio==0.11.0. Can you already address it?
